[build]
target = "x86_64-nonos.json"

[target.x86_64-nonos.json]
rustflags = [
  "-C", "force-frame-pointers=yes",
  "-C", "link-arg=-nostdlib",
  "-C", "link-arg=-static",
  "-C", "link-arg=--gc-sections",
  "-C", "link-arg=-z",
  "-C", "link-arg=max-page-size=0x1000",
]
